In [1]:
import skopt
from smallCombinerBigMagnets import *

In [2]:
func,lattice=compute_Sol(1e-5,25.0,1000,50)

[ 9.56582288e-03  2.70428594e-03 -1.99229731e+02  1.76888805e+01
  9.86584842e-01]
[ 8.25857372e-03 -2.06403251e-03 -1.99747827e+02  1.09697220e+01
  3.66176146e+00]
[ 1.09212481e-02  1.24843594e-03 -1.99776656e+02  1.05958407e+01
  4.69909852e+00]
[ 1.23051063e-02 -1.72596565e-03 -1.99652695e+02  1.22034734e+01
 -3.16595490e+00]
[ 9.14528364e-03  1.48538381e-04 -1.99460405e+02  1.46972714e+01
 -2.08770860e+00]
[ 1.09854850e-02 -2.16303697e-03 -1.99567883e+02  1.33034052e+01
 -1.33638157e+00]
[ 1.00535538e-02  1.71105578e-03 -1.99638973e+02  1.23814333e+01
  1.42344384e-01]
[ 1.08692006e-02 -2.72129785e-03 -1.99325406e+02  1.64480727e+01
 -3.29475876e+00]
[ 7.71438768e-03  2.69331353e-03 -1.99050112e+02  2.00183467e+01
  3.08397348e+00]
[ 9.14750645e-03 -2.41396738e-03 -1.99266449e+02  1.72126848e+01
 -5.98475063e-01]
[ 8.05529467e-03 -2.89381300e-05 -1.99766043e+02  1.07334724e+01
  4.09320402e+00]
[ 8.87331724e-03  9.75133726e-04 -1.99552840e+02  1.34984904e+01
  2.00680212e-01]
[ 1.

[ 9.38287128e-03  1.39800107e-03 -1.99286108e+02  1.69577249e+01
  4.31554914e+00]
[ 1.22365406e-02  3.99631952e-04 -1.99287362e+02  1.69414646e+01
  3.98386467e+00]
[ 9.71525060e-03 -1.03923144e-03 -1.99784169e+02  1.04983958e+01
  3.26551074e+00]
[ 1.21168937e-02 -2.37327293e-03 -1.99348998e+02  1.61421062e+01
 -3.60183018e-01]
[ 8.03537913e-03  2.88340893e-03 -1.99627425e+02  1.25312097e+01
 -4.32765820e+00]
[ 1.08837537e-02  1.43320022e-03 -1.99767538e+02  1.07140792e+01
  1.58717639e+00]
[ 1.05095316e-02 -2.38040988e-03 -1.99659846e+02  1.21107377e+01
  6.79742973e-01]
[ 9.09811626e-03  2.62989486e-03 -1.99163041e+02  1.85537760e+01
  4.83567207e+00]
[ 8.87864669e-03  2.81834164e-03 -1.99460952e+02  1.46901810e+01
 -1.52481205e+00]
[ 7.62643608e-03 -2.68340849e-03 -1.99260469e+02  1.72902369e+01
 -4.20710056e-01]
[ 8.68033988e-03  6.83821916e-04 -1.99598086e+02  1.29117026e+01
  7.76317543e-01]
[ 9.47410698e-03  1.94131334e-03 -1.99161537e+02  1.85732775e+01
 -2.26496019e-01]
[ 9.

In [3]:
from SwarmTracer import SwarmTracer
swarmTracer=SwarmTracer(lattice)

In [4]:
swarmNew=swarmTracer.initialize_Swarm_At_Combiner_Output(.15,1.0,0.0)

In [5]:
for particle in swarmNew:
    print(particle.q,particle.clipped)

[-0.15220915 -0.01778686 -0.00708655] True
[-0.15210964 -0.01649631  0.00694735] True
[-0.4036347   0.00640174 -0.0060366 ] True
[-0.29212153 -0.00846141  0.00602227] True
[-2.71345204  0.19898997 -0.00600302] True
[-0.20232826 -0.01587273  0.006018  ] True
[-0.26504826 -0.00458735 -0.00600417] True
[-0.15251903 -0.02180576  0.00632718] True
[-0.15175366 -0.01187967 -0.00633094] True
[-0.15213294 -0.01679855  0.00642531] True
[-1.39644171e+00  1.05218930e-01 -4.43775896e-04] True
[-0.45041481  0.01766734 -0.00603759] True
[-0.15236463 -0.01980327  0.00615008] True
[-0.21484231 -0.01915627 -0.00600416] True
[-0.26631808  0.0023951   0.0060294 ] True
[-0.35844465  0.00751691  0.00602292] True
[-1.21381329  0.08213578 -0.00600636] True
[-0.15181699 -0.01270103 -0.00907711] True
[-0.25998381  0.00448375 -0.00601047] True
[-0.17460301 -0.02249881  0.00603156] True
[-0.49372884  0.00813298 -0.00601033] True
[-0.41673625  0.01369313  0.00600469] True
[-2.13825822  0.13744112  0.00600016] True

[-0.15262454 -0.0231741   0.0065034 ] True
[-0.15255908 -0.02232515  0.00754978] True
[-0.30859171 -0.00777586  0.00603854] True
[-0.15214278 -0.01692613 -0.00714471] True
[-0.15234467 -0.01954441  0.00832717] True
[-0.32517923  0.00956007  0.00600544] True
[-0.1529867  -0.02787093  0.00704441] True
[-0.35028621  0.00681886 -0.0060166 ] True
[-0.49733759  0.01365441  0.00600354] True
[-0.50126792  0.01440895  0.00600089] True
[-0.15214339 -0.01693408 -0.00688076] True
[-0.15219804 -0.01764286  0.00648136] True
[-0.34142895 -0.00354246  0.0060064 ] True
[-0.76006352  0.03762832 -0.00600693] True
[-0.44857378  0.01670392  0.00600697] True
[-0.72375741  0.02269691  0.00600522] True
[-0.28746575 -0.00198828  0.00600555] True
[-0.15229372 -0.01888369 -0.00734543] True
[-0.15188017 -0.01352042 -0.00758674] True
[-0.23516054 -0.01482571 -0.00603158] True
[-0.47591852  0.00865394 -0.00603594] True
[-0.39343684  0.00693946  0.00602261] True
[-0.28059591  0.00345556 -0.00601909] True
[-0.1523329

In [6]:
for particle in swarm:
    print(particle.qi)

NameError: name 'swarm' is not defined

In [ ]:
def wrap(y,z):
    return fitFunc(y,z,0.0,0.0)

bounds=np.asarray([(-3.0,3.0),(-3.0,3.0)])*1e-3*.9
plotxArr=np.linspace(bounds[0][0],bounds[0][1],num=100)
plotyArr = np.linspace(bounds[1][0], bounds[1][1], num=100)
image=np.empty((plotxArr.shape[0],plotyArr.shape[0]))
for i in range(plotxArr.shape[0]):
    for j in range(plotyArr.shape[0]):
        image[j,i]=wrap(plotxArr[i],plotyArr[j])

image=np.flip(image,axis=0)
extent=[bounds[0][0],bounds[0][1],bounds[1][0],bounds[1][1]]
plt.imshow(image,extent=extent)
image.mean(),image.max(),image.min()

In [ ]:
(3**4/500)**.25