In [1]:
from helperTools import *
from latticeElements.utilities import ElementTooShortError
from latticeModels import make_Ring_And_Injector, RingGeometryError, InjectorGeometryError
from latticeModels_Parameters import optimizerBounds_V1_3,injectorParamsOptimalAny,ringParamsOptimal_V3
from storageRingModeler import StorageRingModel,make_optimal_solution_model



model=make_optimal_solution_model()

In [13]:
bumpLens1=model.lattice_injector.elList[0]
bumpLens2=model.lattice_injector.elList[2]
bumpLens1,bumpLens2
qTest=np.array([10e-3,10e-3,10e-3])
bumpLens1.force(qTest)

array([-122.80063132, -112.3854643 , -103.80544671])

In [14]:
model.lattice_injector.use_mag_errors=True
bumpLens1=model.lattice_injector.elList[0]
bumpLens1.build_fast_field_helper([])
bumpLens1.force(qTest)

array([-113.28192786,  -77.70915157, -125.99614615])

In [15]:
model.lattice_injector.use_mag_errors=True
bumpLens1=model.lattice_injector.elList[0]
bumpLens1.build_fast_field_helper([])
bumpLens1.force(qTest)

array([-143.70990012, -137.21425958,  -75.01386005])